# cSpell: disable
version: "2"

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  # standard = errcheck, govet, ineffassign, staticcheck, unused
  default: standard
  enable:
    - copyloopvar
    - exptostd
    - gocritic
    - intrange
    - mirror
    - misspell
    - modernize
    - perfsprint
    - usestdlibvars
  settings:
    gocritic:
      enabled-tags:
        - performance
      disabled-checks:
        - hugeParam
        - rangeValCopy

formatters:
  enable:
    - gofmt
    - goimports
